In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

import pandas as pd
import re

data_frame = pd.read_csv("spam.csv", encoding='latin-1') #  a base dados é csv, ele le e armazena na tabela
# print("Primeiras linhas:")
# display(data_frame.head())
# display("Colunas disponiveis:", data_frame.columns.tolist())  # para saber qual o nome das colunas e selecionar apenas as que eu usarei

# tratamento do data frame
data_frame.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis=1, inplace=True)
display(data_frame)

        v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [55]:
def process_text(text:str) -> str:
    
    text = text.lower()
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    return text

# aqui eu crio uma nova coluna com o texto processado na minha funcao
data_frame['processed_text'] = data_frame['v2'].apply(process_text)

# removo a coluna antiga
data_frame.drop(['v2'], axis=1, inplace=True)

# # codificacao da coluna 'v1'
# codificador1 = LabelEncoder()
# data_frame['processed_text'] = codificador1.fit_transform(data_frame["processed_text"])

# y -> é a coluna da base de dados que eu quero prever
y = data_frame["v1"]
# x -> as colunas da base de dados que eu vou usar pra fazer a previsão
x = data_frame.drop(columns=["v1"])

display(data_frame)

        v1                                     processed_text
0      ham  go until jurong point crazy available only in ...
1      ham                            ok lar joking wif u oni
2     spam  free entry in  a wkly comp to win fa cup final...
3      ham        u dun say so early hor u c already then say
4      ham  nah i dont think he goes to usf he lives aroun...
...    ...                                                ...
5567  spam  this is the nd time we have tried  contact u u...
5568   ham                 will  b going to esplanade fr home
5569   ham  pity  was in mood for that soany other suggest...
5570   ham  the guy did some bitching but i acted like id ...
5571   ham                          rofl its true to its name

[5572 rows x 2 columns]

In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split


# Converter rótulos para binário (0 = ham, 1 = spam) na coluna label
data_frame['label'] = data_frame['v1'].map({'ham': 0, 'spam': 1})
display(data_frame)

# vetorização
vectorizer = TfidfVectorizer(max_features=3000)  # Limitar a 3000 features para otimização
X = vectorizer.fit_transform(data_frame['processed_text']).toarray()
y = data_frame['label']

# Divisão em conjuntos de treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# modelo escolhido: Naive Bayes
model = MultinomialNB()
model.fit(X_train, y_train)

# Previsões no conjunto de teste
y_pred = model.predict(X_test)

# previsoes dos testes
accuracy = accuracy_score(y_test, y_pred)
display(accuracy) # 97%
precision = precision_score(y_test, y_pred)
display(precision) # 1
recall = recall_score(y_test, y_pred)
display(recall) # 81%
f1 = f1_score(y_test, y_pred)
display(f1) # 89%

        v1                                     processed_text  label
0      ham  go until jurong point crazy available only in ...      0
1      ham                            ok lar joking wif u oni      0
2     spam  free entry in  a wkly comp to win fa cup final...      1
3      ham        u dun say so early hor u c already then say      0
4      ham  nah i dont think he goes to usf he lives aroun...      0
...    ...                                                ...    ...
5567  spam  this is the nd time we have tried  contact u u...      1
5568   ham                 will  b going to esplanade fr home      0
5569   ham  pity  was in mood for that soany other suggest...      0
5570   ham  the guy did some bitching but i acted like id ...      0
5571   ham                          rofl its true to its name      0

[5572 rows x 3 columns]

0.9748878923766816

1.0

0.8133333333333334

0.8970588235294118